# Generated by Django 5.2.8 on 2025-11-26 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='lessons',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_title', models.CharField(max_length=255)),
                ('lesson_type', models.JSONField()),
                ('content_url', models.CharField(max_length=255)),
                ('order_position', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
            ],
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('grade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_title', models.CharField(max_length=255)),
                ('assignment_description', models.CharField(max_length=500)),
                ('due_date', models.DateTimeField()),
                ('max_score', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=255)),
                ('quiz_content', models.JSONField()),
                ('max_score', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('submission_content', models.CharField(max_length=500)),
                ('date_submitted', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('date_graded', models.DateTimeField()),
                ('graded_by', models.IntegerField()),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assignment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
