# Generated by Django 5.2.8 on 2025-12-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251203_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='lessons',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='content_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='order_position',
            field=models.IntegerField(),
        ),
    ]
