# Generated by Django 5.2.8 on 2025-12-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lessons_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
