# Generated by Django 5.2.8 on 2025-12-01 21:24

from django.db import migrations


def seed_roles(apps,schema_editor):
    Role = apps.get_model('api', 'Role')
    Role.objects.get_or_create(role_name='student', defaults={'role_description': 'A student role'})
    Role.objects.get_or_create(role_name='instructor', defaults={'role_description': 'An instructor role'})
    Role.objects.get_or_create(role_name='admin', defaults={'role_description': 'An admin role'})
    Role.objects.get_or_create(role_name='superadmin', defaults={'role_description': 'A super admin role'})


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_categories_role_remove_userprofile_role_id_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_roles)
    ]
