# Generated by Django 5.2.8 on 2025-12-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_courses_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_categories',
            options={'ordering': ['category_name'], 'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['order_position']},
        ),
        migrations.AlterField(
            model_name='course_categories',
            name='category_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course_categories',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='api.course_categories'),
        ),
    ]
